### ISSUE TITLE
feature request: configure different CNI

### ISSUE THREAD

**Issue by STRRL** [medyagh/setup-minikube#26]
I wish we could setup which cni plugin to use like 

```yaml
    - name: Setup minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker
        cni: flannel
```
