### ISSUE TITLE
cpus and memory is not valid 

### ISSUE THREAD

**Issue by Slach** [medyagh/setup-minikube#40]
I tried the following github actions
```
      - uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.23.12
          cpus: max
          memory: max
```
and got 
```
Warning: Unexpected input(s) 'cpus', 'memory', valid inputs are ['minikube-version', 'driver', 'container-runtime', 'kubernetes-version']
```

Need I wait a next release to apply these parameters?
