### ISSUE TITLE
conventional major version tag

### ISSUE THREAD

**Issue by qrkourier** [medyagh/setup-minikube#648]
This is a useful Action! Presently, it's necessary for me to upgrade, but that consumer step can be eliminated by adopting the major version tag convention of GitHub Actions.

Please consider publishing a major version tag, e.g. `v1` that continually represents the latest, stable, reverse-compatible release version.

It's meaningful to consumers who can rest assured that breaking changes will not be introduced until `v2`.

```yaml
name: Keep the major version tag up-to-date
on:
  release:
    types: [published]

permissions:
  contents: write

# move the major version tag to the latest release, e.g., v1, to enable
# consumers to subscribe to the latest reverse-compatible release
jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
          prefer_branch_releases: false 
```
