### ISSUE TITLE
Add nodes input

### ISSUE THREAD

**Issue by zachspar** [medyagh/setup-minikube#698]
Would like to be able to specify `--nodes` via action input (without having to use `start-args`:
```yaml
      - name: Setup minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: kvm2
          container-runtime: containerd
          nodes: 3
```
